### ISSUE TITLE
Multitasking/multithreading/multiprocessing 

### ISSUE THREAD

**Issue by backfromhiatus** [Tukeque/URCL-OS#4]
How does it work? context switching? Is it coop or preemptive? Maximum threads? processes?

**Comment by backfromhiatus** [comment]
hi?

**Comment by Verlio-H** [comment]
I believe this was answered over discord years ago, but urclos actually recently switched completely to preemptive multitasking. Urclos has no concept of threads but processes act much like threads in other operating systems due to the lack of virtual memory. There is currently a process limit of 16 but that is easy to change and in the near future I plan on making it unlimited.
